Update french translation
chubin/wttr.in pull request #976
Opened 2024-03-17 17:04 UTC by kleyeus

When i run `fr.wttr.in` nearly half of the weather conditions are still in **english**.
See attached file :  [JSON French.json](https://github.com/chubin/wttr.in/files/14628192/JSON.French.json)

I tried another language `es.wttr.in` and everything is translated in **spanish** as expected.
See attached file :  [JSON Spanish.json](https://github.com/chubin/wttr.in/files/14628197/JSON.Spanish.json)

Comparing translation.txt, french translation txt's structure was different from spanish one so i copied spanish structure and put the old french translations in place.

2024-05-17 19:48 UTC, flobsx requested changes

2024-05-17 19:48 UTC, flobsx commented on share/translations/fr.txt
> +114: Temps clair: Clear
```
113: Temps clair: Clear
```
Code 114 not used in source code, 113 is the one (looking at other translation)

2024-05-17 19:48 UTC, flobsx commented on share/translations/fr.txt
> +176: Pluies éparses possibles: Patchy rain possible
```
176: Pluies éparses à proximité: Patchy rain nearby  
176: Pluies éparses possibles: Patchy rain possible
``` 
The `nearby` variation also exists.

2024-05-17 19:48 UTC, flobsx commented on share/translations/fr.txt
> +200: Orages possibles: Thundery outbreaks possible
```
200: Orages à proximité: Thundery outbreaks in nearby 
200: Orages possibles: Thundery outbreaks possible
``` 
The `nearby` variation also exists.

2024-05-17 19:48 UTC, flobsx commented on share/translations/fr.txt
> +386: Pluies orageuses légères et éparses: Patchy light rain with thunder
```
386: Pluies orageuses légères et éparses: Patchy light rain with thunder
386: Pluies orageuses légères et éparses à proximité: Patchy light rain in area with thunder 
``` 
The `nearby` variation also exists.

2024-05-17 19:48 UTC, flobsx commented on share/translations/fr.txt
> +389: Pluies orageuses modérées à fortes: Moderate or heavy rain with thunder
```
389: Pluies orageuses modérées à fortes à proximité: Moderate or heavy rain in area with thunder 
389: Pluies orageuses modérées à fortes: Moderate or heavy rain with thunder
``` 
The `nearby` variation also exists.

2024-05-17 19:48 UTC, flobsx commented on share/translations/fr.txt
> +395: Chutes de neige orageuses modérées à fortes: Moderate or heavy snow with thunder
```
395: Chutes de neige orageuses modérées à fortes à proximité: Moderate or heavy snow in area with thunder 
395: Chutes de neige orageuses modérées à fortes: Moderate or heavy snow with thunder
``` 
The `nearby` variation also exists.

2024-09-26 06:58 UTC, torgeir commented
I believe there might be other issues causing a similar experience for more languages, it seems e.g. for `nb` (norwegian) that the correct translations do exist, but they are not used

```sh
> curl -s "https://nn.wttr.in/trondheim?format=j1" | jq '.current_condition[0].weatherCode'
"302"
```

[Translation for 302 do exist for `nb` (norwegian)](https://github.com/chubin/wttr.in/blob/235581925fa2e09a42e9631e2c23294a1972ee0e/share/translations/nb.txt#L23), but still the result is in english

```sh
> curl -s "https://nb.wttr.in/trondheim?format=j1" | jq '.current_condition[0].lang_nb[0].value'
"Rain shower"
```

2025-01-22 19:54 UTC, merged